### ISSUE TITLE
Timers and Competitive

### ISSUE THREAD

**Issue by Gensokian** [Hypnootize/hypnotize-hud#13] opened 2018-05-26 18:55 UTC
I really like the Design of the Timers but they are quite unhandy when you have to constantly look in the top left corner (as for normally in the middle top). I'd suggest moving that in the top center as that would make game-timing a lot easier

(example, not quite good but i don't know tf2 hud coding :/)
![image](https://user-images.githubusercontent.com/9213561/40579253-9d86a64e-6123-11e8-9a89-741e67a0decd.png)

Another thing I realised is when pressing TAB to open the scoreboard; the timer appears but without numbers in the top left (see attached screenshot)
![image](https://user-images.githubusercontent.com/9213561/40579301-b8ee55b6-6124-11e8-8109-b3c852872cef.png)

About competitive:

I also saw that when playing "competitively" with the commands
mp_tournament 1
mp_tournament_readymode 0
The little buttons which define the Team Ready stat (top middle) are not labeled correctly
![image](https://user-images.githubusercontent.com/9213561/40579369-255d51a6-6126-11e8-894f-a704c1e8f53e.png)

When playing in stopatch mode, the little indicator on the left of the stopwatch (top left next to the timer) in payload (activated by the command: "mp_tournament_stopwatch 1") is not allignet correctly (again see screenshot)
![image](https://user-images.githubusercontent.com/9213561/40579381-674eddbe-6126-11e8-8e58-ff1c12e206c8.png)

Also a minor thing is that killstreak notifications at the top gets overlayed by the ready-indicator in the top (also another screenshot :D)
![image](https://user-images.githubusercontent.com/9213561/40579406-f097ff88-6126-11e8-916b-aebf2f2d9ed2.png)

Also a really small thing, the "Your X" label on the gibs when beeing exploded with small health/with tf_playergib 2 are not designet yet. Don't mind it, just wanted to add it :)
![image](https://user-images.githubusercontent.com/9213561/40579497-95c7d64e-6128-11e8-8e7c-511ac8399330.png)

_Sorry for dumpin these manny issues at ya._

Cheers!

**Comment by Hypnootize** [comment] 2018-07-02 17:24
I like where the koth timers/normal cp timer is I'm probably not gonna change it anytime soon!

The timeleft and tournament labels problems are caused by your resolution being really high (its fine for me on 1080p) and sadly i can't test it, i can still try to make a little better when i can since i know why is happening.

The stopwatch timer thing should be fixed now

I'll add a customized indicator for the "your hand" label etc as soon as i get i good idea on how to do it lol.

**Closed as completed by Hypnootize** 2018-07-02 17:24 UTC

**Comment by Gensokian** [comment] 2018-07-02 17:30
Just a little addition to the screen resolution;

What I used earlier in the days was http://www.teamfortress.tv/17291/sourceres which allows to go beyond the screen resolutions and downscales it.

But thanks for the heads up!

**Comment by Hypnootize** [comment] 2018-07-02 18:07
oooh thats actually really cool I didn't know about it ty, I'll see if I can fix it for good then.
